# Theme Configuration
[theme.color_palette]
background = "black"
foreground = "white"
muted = "dark_gray"
highlight = "magenta"
accent_primary = "blue"
accent_secondary = "magenta"
accent_tertiary = "cyan"
accent_quaternary = "yellow"
info = "cyan"
warning = "yellow"
error = "red"
