[niri]

[piri.plugins]
empty = true
window_order = true
workspace_rule = true
scratchpads = false
window_rule = false
autofill = false
singleton = false
swallow = false

[piri.workspace_rule]
auto_width = [
    "100%",
    "100%",
    [
        "100%",
        "50%",
        "50%",
    ],
    [
        "100%",
        "50%",
        "70%",
        "80%",
    ],
    "70%",
]
auto_tile = false
auto_fill = false
auto_maximize = false

[piri.window_order]
enable_event_listener = true # Enable event listening for automatic reordering
default_weight = 50          # Default weight for unconfigured windows
# workspaces = ["1", "2", "dev"]  # Optional: only apply to specific workspaces (empty = all)

[window_order]
zen-browser = 100
Vmware = 99
virt-manager = 98
dolphin = 97
rmpc = 96
mpv = 95
vlc = 94
foot = 49
kitty = 48

[empty.Net]
command = "zen-browser"
