[niri]

[piri.plugins]
empty = true
window_order = true
workspace_rule = true
scratchpads = false
window_rule = false
autofill = false
singleton = false
swallow = false

[piri.workspace_rule]
auto_width = ["100%", "70%", ["50%", "50%"], "50%", "50%"]
auto_tile = false
auto_fill = false
auto_maximize = false

[piri.window_order]
enable_event_listener = true # Enable event listening for automatic reordering
default_weight = 0           # Default weight for unconfigured windows

[window_order]
zen-browser = 100
Vmware = 99
virt-manager = 98
dolphin = 80
rmpc = 79
foot = 75

[empty.Net]
command = "zen-browser"
