# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"
# ############
#   Notes   #
# ############
# This config assumes you have a Nerd Font installed and enabled in your terminal.
# I use 'FiraCode Nerd Font Mono', but you should be able to use any Nerd Font you like.
# ###############
#   Settings   #
# ###############
# Inserts a blank line between shell prompts
add_newline = true
# Maximum time it may take to produce the prompt
command_timeout = 3000
# #######################
#   Webber's colours   #
# #######################
# Bright pink: (bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}})
# Middle pink, bright text: (bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}})
# Middle pink, faded text: (bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}})
# Dark pink, regular text: (bg:{{colors.secondary_container.default.hex}} fg:{{colors.on_secondary_container.default.hex}})
# Dark pink, highlighted: (bg:{{colors.secondary_container.default.hex}} fg:{{colors.primary.default.hex}})
# ##############
#   Prompts   #
# ##############
# Right prompt. This is displayed on the right side of the terminal.
# Colours (i.e. bg and fg) are always listed from left to right.
#
# Note: Not supported in Powershell
# @see: https://starship.rs/advanced-config/#enable-right-prompt
# Left prompt. This is displayed on the left side of the terminal.
# Colours (i.e. bg and fg) are always listed from left to right.
format = """
[ÓÇ∂](bg:#transparent fg:{{colors.primary.default.hex}})\
$os\
[ÓÇ¥](fg:{{colors.primary.default.hex}} bg:{{colors.primary_container.default.hex}})\
$directory\
${custom.pregit}\
$git_branch\
$git_state\
$git_status\
${custom.postgit}\
${custom.nogit}\
$package\
$python\
$lua\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$bun\
$nim\
$rust\
$scala\
$docker_context\
$character\
"""

# #######################
#   Special sections   #
# #######################

# Exit code indicator
[character]  # The name of the module we are configuring is 'character'
success_symbol = "[ÓÇ∂](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ÓØÜ](bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}})[ÓÇ¥](fg:{{colors.primary.default.hex}} bg:transparent)"
error_symbol = "[ÓÇ∂](bg:{{colors.primary_container.default.hex}} fg:{{colors.error.default.hex}})[Ó™á](bg:{{colors.error.default.hex}} fg:{{colors.on_error.default.hex}})[ÓÇ¥](fg:{{colors.error.default.hex}} bg:transparent)"
vimcmd_symbol = "[ÓÇ∂](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ÓüÖ](bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}})[ÓÇ¥](fg:{{colors.primary.default.hex}} bg:transparent)"
format = "$symbol "

# cross-platform way to check if we are in a git repo, takes 200ms
[custom.nogit]
when = ''' git rev-parse --git-dir ; test $? = False '''
format = "[ ](bg:{{colors.primary_container.default.hex}})"
disabled = true

# Either `Administrator`, `root` or the current user's username.
[username]
show_always = true
style_user = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"
style_root = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"
format = "[ $user]($style)"
disabled = false

# Displays a symbol that represents the current operating system
[os]
style = "bg:{{colors.primary.default.hex}} fg:{{colors.on_primary.default.hex}}"
format = "[Ê≠ªShin]($style)"
disabled = false  # This doesn't work in pwsh in Webstorm terminal.

[os.symbols]
Alpaquita = "Ó™¢ "
Alpine = "ÔåÄ "
AlmaLinux = "Ôåù "
Amazon = "Ôâ∞ "
Android = "ÔÖª "
Arch = "ÔåÉ "
Artix = "Ôåü "
CachyOS = "ÔåÉ "
CentOS = "ÔåÑ "
Debian = "ÔåÜ "
DragonFly = "Óäé "
Emscripten = "ÔàÖ "
EndeavourOS = "ÔÜó "
Fedora = "Ôåä "
FreeBSD = "Ôåå "
Garuda = "Û∞õì "
Gentoo = "Ôåç "
HardenedBSD = "Û∞ûå "
Illumos = "Û∞à∏ "
Kali = "Ôåß "
Linux = "Ôåö "
Mabox = "Ó¨© "
Macos = "ÔåÇ "
Manjaro = "Ôåí "
Mariner = "Ôáç "
MidnightBSD = "ÔÜÜ "
Mint = "Ôåé "
NetBSD = "ÔÄ§ "
NixOS = "Ôåì "
Nobara = "ÔéÄ "
OpenBSD = "Û∞à∫ "
openSUSE = "Ôåî "
OracleLinux = "Û∞å∑ "
Pop = "Ôå™ "
Raspbian = "Ôåï "
Redhat = "Ôåñ "
RedHatEnterprise = "Ôåñ "
RockyLinux = "Ôå´ "
Redox = "Û∞Äò "
Solus = "Û∞†≥ "
SUSE = "Ôåî "
Ubuntu = "Ôåõ "
Unknown = "Ôà≠ "
Void = "ÔåÆ "
Windows = "Û∞ç≤ "

# The current directory
[directory]
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = ""

[hostname]
ssh_symbol = "Ó¨Å"

[memory_usage]
symbol = "Û∞çõ"

[time]
disabled = false
time_format = "%R"  # Hour:Minute Format
style = "bg:{{colors.primary_container.default.hex}}"
format = "[$time]($style)"

# ######################
#   Version control   #
# ######################

[git_branch]
symbol = "Ôêò"
style = "bg:{{colors.secondary_container.default.hex}} fg:{{colors.on_secondary_container.default.hex}}"
format = "[ÓÇ¥](fg:{{colors.primary_container.default.hex}} bg:{{colors.secondary_container.default.hex}})[ $symbol](bg:{{colors.secondary_container.default.hex}} fg:{{colors.primary.default.hex}})[ $branch ]($style)"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[üçí PICKING](bg:{{colors.secondary_container.default.hex}} fg:bold red)"
rebase = "[Ó©§ REBASING](bg:{{colors.secondary_container.default.hex}} fg:bold green)"
merge = "[Óúß MERGING](bg:{{colors.secondary_container.default.hex}} fg:bold yellow)"
bisect = "[üîç BISECTING](bg:{{colors.secondary_container.default.hex}} fg:bold blue)"
am = "[AM](bg:{{colors.secondary_container.default.hex}} fg:bold green)"
am_or_rebase = "[AM/REBASE](bg:{{colors.secondary_container.default.hex}} fg:bold green)"
revert = "[Û∞ïç REVERTING](bg:{{colors.secondary_container.default.hex}} fg:bold red)"

[git_metrics]
added_style = "bg:{{colors.secondary_container.default.hex}} fg:{{colors.tertiary.default.hex}}"
deleted_style = "bg:{{colors.secondary_container.default.hex}} fg:{{colors.error.default.hex}}"
format = "([+$added ]($added_style))([-$deleted ]($deleted_style))"
disabled = false

[git_status]
style = "bg:{{colors.secondary_container.default.hex}} fg:{{colors.primary.default.hex}}"
conflicted = "="  # This branch has merge conflicts.
ahead = "Ó™†"
behind = "Ó™ù"
diverged = "Û±°∑"
up_to_date = ""
untracked = "?"
stashed = "ÔÖï"
modified = "ÔëÑ"
staged = "Ó´¥"
renamed = "¬ª"
deleted = "‚úò"
format = "([($all_status )($ahead_behind )]($style))[ÓÇ∂](bg:{{colors.secondary_container.default.hex}} fg:{{colors.primary_container.default.hex}})"

[fossil_branch]
symbol = "Ôêò"

[hg_branch]
symbol = "Ôêò"

[pijul_channel]
symbol = "Ôêò"

# ###########################
#   Contexts (canonical)   #
# ###########################

[nodejs]
symbol = "Óúò"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[bun]
symbol = "Û∞Öü"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[docker_context]
symbol = "Ôåà"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ (context) ]($style)"

[package]
format = "($style)[> $symbol$version ]($style)"
symbol = "üì¶ "
version_format = "v${raw}"
style = "bold 208 bg:{{colors.primary_container.default.hex}}"
display_private = false
disabled = true
# ###############
#   Contexts   #
# ###############

[aws]
symbol = "ÓåΩ"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[c]
symbol = "Óòû"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[conda]
symbol = "ÔÑå"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[dart]
symbol = "Óûò"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[elixir]
symbol = "Óò≠"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[elm]
symbol = "Óò¨"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[golang]
symbol = "Óòß"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[gradle]
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[haskell]
symbol = "Óù∑"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[haxe]
symbol = "Óô¶"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[java]
symbol = "Óâñ"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[julia]
symbol = "Óò§"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[kotlin]
symbol = "Óò¥"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[lua]
symbol = "Óò†"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[ocaml]
symbol = "Óô∫"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[perl]
symbol = "Óôæ"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[php]
symbol = "Óòà"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[python]
symbol = "Óàµ"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[rlang]
symbol = "Û∞üî"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[ruby]
symbol = "Óûë"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[rust]
symbol = "Óû®"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[scala]
symbol = "Óú∑"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[swift]
symbol = "Óùï"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

[zig]
symbol = "Óö©"
style = "bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}}"
format = "[$symbol](bg:{{colors.primary_container.default.hex}} fg:{{colors.primary.default.hex}})[ ($version) ]($style)"

# ############
#   Other   #
# ############

[nix_shell]
symbol = "Ôåì"
