[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromBottom"
command = "kitty --class kitty-dropterm fish -c 'tmux new -A -s scratch-term'"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
