[wallpaper]
custom_paths = [
    "$HOME/Pictures/Wallpapers",
] # List of paths to search for wallpapers
backend = "swww" # Wallpaper backend, example: swww, hyprpaper, pcmanfm, feh, etc.

[wallpaper.swww]
# swwwallselect.sh configuration
framerate = 60 # transition framerate
duration = 1   # transition duration
# Transition type [ none | simple | fade | left | right | top | bottom | wipe | wave | grow | center | any | outer | random ]
transition_next = "grow"      # transition type for next wallpaper
transition_prev = "outer"     # transition type for previous wallpaper
transition_default = "simple" # transition type for default wallpaper


# NOTE: 
# for [rofi.*] 
# style <--script's built-in styles, also accepts themes from rofi-theme-selector

[rofi.hyprlock]
# 'hyprlock.sh select' configuration
scale = 10

[rofi.glyph]
# glyph-picker.sh configuration
scale = 10

[rofi.launch]
scale = 10            # Scaling for launch.
drun_args = []        # Additional arguments for drun mode.
run_args = []         # Additional arguments for run mode.
window_args = []      # Additional arguments for window mode.
filebrowser_args = [] # Additional arguments for filebrowser mode.

[rofi.cliphist]
# cliphist.sh configuration
scale = 10

[rofi.wallpaper]
#swwwallselect.sh configuration
scale = 7

[rofi.emoji]
# emoji-picker.sh configuration
style = 2
scale = 11

[rofi.theme]
# themeselect.sh configuration
scale = 6

[wlogout]
style = 2

[keybind.hint]
# keybind.hint.py configuration

[screenshot]
annotation_tool = "swappy"     # Annotation tool for screenshots.
annotation_pre_command = []    # Pre command for annotation tool.
annotation_post_command = [""] # Post command for annotation tool.

[waybar]
font = "JetBrainsMono Nerd Font" # Font for waybar.
scale = 10                       # Total scaling for waybar.
icon_size = 10                   # Icon size for waybar.

[weather]
temperature_unit = 'c'  # Temperature unit to Â°C or Â°F ('c' or 'f')
time_format = '12h'     # Time format ('12h or 24h')
windspeed_unit = 'km/h' # Windspeed unit ('kh/h' or 'mph')
show_icon = true        # Show the weather icon in waybar
show_location = true    # Show the location in waybar
show_today = true       # Detailed description of today in tooltip
forecast_days = 3       # Number of days to show forecast (0-3)
location = ''           # Location/coordinates string for the weather output


[cava.stdout]
max_instances = 3 # Maximum number of cava instances.
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"  # Bar characters for cava.
width = 20        # Width of the cava output.
range = 7         # Number of bars minus one.
standby = "ðŸŽ¶"     # Standby character for cava.

# 'cava.sh hyprlock' configuration.
[cava.hyprlock]
max_instances = 3 # Maximum number of cava instances.
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"  # Bar characters for cava.
width = 20        # Width of the cava output.
range = 7         # Number of bars minus one.
standby = "ðŸŽ¶"     # Standby character for cava.

# 'cava.sh waybar' configuration.
[cava.waybar]
max_instances = 3 # Maximum number of cava instances.
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"  # Bar characters for cava.
width = 20        # Width of the cava output.
range = 7         # Number of bars minus one.
standby = "ðŸŽ¶"     # Standby character for cava.

[volume]
# volumecontrol.sh configuration
notify = true     # Useful for systems that have their own OSD
steps = 5         # Number of steps to increase/decrease volume
boost = true      # Enable volume boost
boost_limit = 150 # Volume boost limit // Don't kill your ears/speakers

[brightness]
# brightnesscontrol.sh configuration
notify = true # Useful for systems that have their own OSD
steps = 5     # Number of steps to increase/decrease brightness


[sysmonitor]
#  sysmonlaunch.sh configuration // System monitor configuration
execute = "btop"                   # Default command to execute // accepts executable or app.desktop
commands = ["btop", "htop", "top"] # Fallback command options


[notification]
# notification script can use this configuration
font = "mononoki Nerd Font" # Font for notifications
font_size = 9               # Font size for notifications

[hyprland]
explorer = "thunar" # File manager.

# [hyprland_start]
# mpris = "mpDris2"

[mediaplayer]
prefix_playing = "ï€"           # Prefix for playing media.
prefix_paused = "ï€  ïŒ"         # Prefix for paused media.
max_length = 70                # Max length of song and artist string.
standby_text = "ï€  Music"      # To display on standby.
artist_track_separator = "â€„ï‘„ " # Separator symbols to display between artist and track.
