[config]

[templates]
# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
# [templates.placeholder]
# input_path = "/home/shin/.config/quickshell/noctalia-shell/Assets/MatugenTemplates/noctalia.json"
# output_path = "/home/shin/.cache/noctalia/placeholder.json"

[templates.starship]
input_path = "~/.config/matugen/templates/starship/starship-colors.toml"
output_path = "~/.config/starship.toml"
post_hook = "bash ~/.local/bin/theme-switch-hook.bash"

# [templates.tmux]
# input_path = "~/.config/matugen/templates/tmux/tmux-colors.conf"
# output_path = "~/.config/tmux/colors.conf"
# post_hook = "tmux source-file ~/.config/tmux/colors.conf >/dev/null 2>&1 || tmux source-file ~/.config/tmux/theme.conf >/dev/null 2>&1 "

# [templates.kitty]
# input_path = "~/.config/matugen/templates/kitty/kitty-colors.conf"
# output_path = "~/.config/kitty/current-theme.conf"
# post_hook = "pkill -SIGUSR1 kitty"

# [templates.foot]
# input_path = "~/.config/matugen/templates/foot/foot"
# output_path = "~/.config/foot/themes/noctalia"

[templates.kde_colors]
input_path = "~/.config/matugen/templates/kde/color.txt"
output_path = "~/.local/state/quickshell/user/generated/color.txt"
post_hook = "~/.config/matugen/templates/kde/kde-material-you-colors-wrapper.sh && plasma-apply-colorscheme noctalia"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland/colors.conf"
output_path = "~/.config/hypr/hyprland/colors.conf"

[templates.nvim-base16]
input_path = "~/.config/nvim/lua/config/matugen-template.lua"
output_path = "~/.config/nvim/colors/matugen.lua"
post_hook = 'pkill -SIGUSR1 nvim'

[templates.rmpc]
input_path = "~/.config/matugen/templates/rmpc/colors.ron"
output_path = "~/.config/rmpc/themes/colors.ron"
