[config]

[templates]
# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
# [templates.placeholder]
# input_path = "/home/shin/.config/quickshell/noctalia-shell/Assets/MatugenTemplates/noctalia.json"
# output_path = "/home/shin/.cache/noctalia/placeholder.json"

[templates.starship]
input_path = "~/.config/matugen/templates/starship/starship-colors.toml"
output_path = "~/.config/starship.toml"
post_hook = "starship init fish | source"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty/kitty-colors.conf"
output_path = "~/.config/kitty/current-theme.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.kde_colors]
input_path = "~/.config/matugen/templates/kde/color.txt"
output_path = "~/.local/state/quickshell/user/generated/color.txt"
post_hook = "~/.config/matugen/templates/kde/kde-material-you-colors-wrapper.sh"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland/colors.conf"
output_path = "~/.config/hypr/hyprland/colors.conf"

[templates.wallpaper]
input_path = "~/.config/matugen/templates/wallpaper.txt"
output_path = "~/.local/state/quickshell/user/generated/wallpaper/path.txt"
